### ISSUE TITLE
[Request] A "reset" command

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [BluCodeGH/MineNPC#3]
So we can reset the NPC on the fly, maybe make it so one NPC can reset another one?

**Comment by BluCodeGH** [comment]
Reset as in go back to the beginning and reset the speech score?

**Note to self:** Need to implement movement reset!

**Comment by ThatNerdyPikachu** [comment]
Yeah

**Comment by BluCodeGH** [comment]
If you don't use movement, the NPC resets automatically 20 seconds after its finished talking, or 15 seconds after the player walks away. You can also use `/execute @e[tag=talks,name=NPCNAME] ~ ~ ~ scoreboard players operation @e[tag=talks,r=0] speech = @e[tag=talks,r=0] speechMax` to reset it.

**Comment by ThatNerdyPikachu** [comment]
Maybe just add a shortcut to that command, like "/reset NPCNAME"

**Comment by BluCodeGH** [comment]
For the movement reset, should the NPC just tp away? That may look weird... Lets DM in dc to discuss more.

**Comment by thebeastgamer25** [comment]
K

**Comment by BluCodeGH** [comment]
Fixed the movement reset. Why should an NPC be able to reset another mid-speech? What is a use-case for that?

**Comment by ThatNerdyPikachu** [comment]
Don't put that in. It was just an idea, I don't like it now

**Comment by BluCodeGH** [comment]
In that case, bug fixed, case closed.
